CC=clang

FLAGS = \
	-I ../ \
	-I ../zmqpp-root/include \
	-Wall \
	-Wextra \
	-Wno-parentheses \
	-Wshadow \
	-Wunreachable-code \
	-g

ifndef RELEASE
	FLAGS +=  \
		-DENABLE_TRACE \
		-O0 \
		-fno-omit-frame-pointer \
		-fsanitize=address
else
	FLAGS +=  \
		-O2 \
		-fomit-frame-pointer
endif

CXXFLAGS = \
	$(FLAGS) \
	-std=c++14

LDFLAGS = \
	-L ../zmqpp-root/lib \
	-lpthread \
	-lstdc++ \
	-lzmq \
	-lzmqpp

ifndef RELEASE
	LDFLAGS += \
		-fsanitize=address
endif
